---
kasten:
  kdrSecretKey: secret/data/hub/kastendr-passphrase

  policyDefaults:
    locationProfileName: my-location-profile
    presetName: daily-backup
    ignoreExceptions: false

  locationProfileDefaults:
    secretKey: secret/data/hub/aws-creds
    immutable: false
    protectionPeriod: 120h0m0s # 5 Days
    s3Region: us-east-1

  locationProfiles:
    location-profile-1:
      name: my-location-profile
      secretKey: secret/data/hub/aws-creds    
      bucketName: rhvp-test-bucket
      immutable: true
      protectionPeriod: 168h0m0s # 7 Days
    location-profile-2:
      name: other-location-profile
      secretKey: secret/data/hub/aws-creds    
      bucketName: rhvp-test-bucket-2